# Generated by Django 4.2.13 on 2024-06-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loanapplication'),
        ),
    ]
